[phases.setup]
nixPkgs = ['maven', 'jdk17']

[phases.build]
cmds = ['cd cafeteria-orders-api && mvn clean package -DskipTests']

[phases.start]
cmd = 'cd cafeteria-orders-api && java -Dserver.port=$PORT -jar target/cafeteria-orders-api-0.0.1-SNAPSHOT.jar'
